name: Run salt tests
on:
  pull_request:

concurrency:
  group: test-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  linux:
    uses: plus3it/actions-workflows/.github/workflows/test-salt-linux.yml@8dbdaec548e7ccadb978c6a2fbc05e5c64625935
    strategy:
      matrix:
        os_version:
          - 8
          - 9
        salt_state:
          - scap.scan
        salt_pillar_root:
          - ./tests/pillar/test-oscap
          - ./tests/pillar/test-scc
    with:
      salt-os-version: ${{ matrix.os_version }}
      salt-state: ${{ matrix.salt_state }}
      salt-pillar-root: ${{ matrix.salt_pillar_root }}

  windows:
    uses: lorengordon/actions-workflows/.github/workflows/test-salt-windows.yml@390b0e345b2e9cd476cfd0b636c69e40ff25a44d
    strategy:
      matrix:
        os_version:
          - windows-2019
          - windows-2022
        salt_state:
          - scap.scan
        salt_pillar_root:
          - ./tests/pillar/test-scc
    with:
      salt-os-version: ${{ matrix.os_version }}
      salt-state: ${{ matrix.salt_state }}
      salt-pillar-root: ${{ matrix.salt_pillar_root }}
